name: Dependencies

on:
  schedule:
    - cron: "47 18 * * *"
  workflow_dispatch:
concurrency:
  # Pushing new changes to a branch will cancel any in-progress CI runs
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Restrict jobs in this workflow to have no permissions by default; permissions
# should be granted per job as needed using a dedicated `permissions` block
permissions: {}

jobs:
  update:
    permissions:
      contents: write # to fetch and commit code
      actions: write # to manually dispatch checks on the pull request
      pull-requests: write # Create pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: stable
          check-latest: true
      - run: |
          latest_commit=$(git ls-remote https://github.com/google/osv-scalibr.git HEAD | cut -f1)
          echo "updating osv-scalibr to $latest_commit"
          go get github.com/google/osv-scalibr@"$latest_commit"
          echo "latest_scalibr_commit=$latest_commit" >> "$GITHUB_ENV"
          go mod tidy
      - run: go test ./cmd/osv-scanner/ -run 'Test_run$' || true
        env:
          TEST_ACCEPTANCE: true
          UPDATE_SNAPS: always
      - uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          token: ${{ secrets.PR_TOKEN_BOT }}
          title: "feat: update osv-scalibr"
          body: >
            This updates `osv-scalibr` to https://github.com/google/osv-scalibr/commit/${{ env.latest_scalibr_commit }}
          branch: "bot/update-scalibr"
          author: "osv-robot <osv-robot@google.com>"
          commit-message: "feat: update osv-scalibr to ${{ env.latest_scalibr_commit }}"
          delete-branch: true
