name: Renovate Config Validator

on:
  push:
    branches: [main, v2]
    paths:
      - "renovate.json"
  pull_request:
    branches: [main, v2]
    paths:
      - "renovate.json"

# Restrict jobs in this workflow to have no permissions by default; permissions
# should be granted per job as needed using a dedicated `permissions` block
permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read # to fetch code (actions/checkout)
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Set up Nodes.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: latest

      - name: Validate Renovate Config
        run: npx --yes --package renovate -- renovate-config-validator
