name: Snapshots

on:
  schedule:
    - cron: "47 12 * * *"
  workflow_dispatch:
concurrency:
  # Pushing new changes to a branch will cancel any in-progress CI runs
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Restrict jobs in this workflow to have no permissions by default; permissions
# should be granted per job as needed using a dedicated `permissions` block
permissions: {}

jobs:
  update:
    permissions:
      contents: write # to fetch and commit code
      actions: write # to manually dispatch checks on the pull request
      pull-requests: write # Create pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: stable
          check-latest: true
      - run: ./scripts/run_tests.sh
        env:
          TEST_ACCEPTANCE: true
          UPDATE_SNAPS: always
      - uses: gr2m/create-or-update-pull-request-action@b65137ca591da0b9f43bad7b24df13050ea45d1b # v1.10.1
        id: create-or-update-pull-request
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          title: "test: update snapshots"
          body: >
            The snapshots have changed, probably due to OSV advisories being changed.

            Please review the differences to make sure that they're expected!
          branch: "bot/update-snapshots"
          author: "another-rex <rexpan@google.com>"
          commit-message: "test: update snapshots"
      - uses: octokit/request-action@dad4362715b7fb2ddedf9772c8670824af564f0d # v2.4.0
        if: steps.create-or-update-pull-request.outputs.result != 'unchanged'
        with:
          route: |
            POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          workflow_id: checks.yml
          ref: bot/update-snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
